const TYPES = {
  CHANGE_DIRECTORY: 'CHANGE_DIRECTORY',

  LIST_FILES: 'LIST_FILES',
  FILES_VIEW: 'FILES_VIEW',
  SELECT_VIEW: 'SELECT_VIEW',

  NAVIGATION: 'NAVIGATION',
  TOGGLE: 'TOGGLE',
  REFRESH: 'REFRESH',
  SORT: 'SORT',

  NEW_FILE: 'NEW_FILE',
  CREATE_FILE: 'CREATE_FILE',
  SHARE_FILE: 'SHARE_FILE',
  RENAME_FILE: 'RENAME_FILE',
  ACTIVE_FILE: 'ACTIVE_FILE',
  DELETE_FILE: 'DELETE_FILE',
  COPY_FILE: 'COPY_FILE',
  MOVE_FILE: 'MOVE_FILE',

  MENU: 'MENU',
  DIALOG: 'DIALOG',

  SPINNER: 'SPINNER',

  SETTINGS: 'SETTINGS',

  SEARCH: 'SEARCH',

  PICK: 'PICK'
};

export default TYPES;
